---
title: Project Title
author: W. Cools
date: last-modified
published-title: "Rendered"
execute:
  echo: FALSE
  message: FALSE
  warning: FALSE
---

<!-- set up -->

```{r}
#| label: x_identification
#| echo: false

name <- "project name"		# CHANGE or get folder name
# label <- "project label"

prjct <- c(name=ifelse(exists('name'),name,basename(here::here())),
	label=ifelse(exists('label'),label,"no label"))
mydata <- 'data.sav'
mydict <- 'dictionary.xlsx'
```

```{r}
#| label: x_functions
#| echo: false
pckgs <- c('tidyverse','gt')
donotshow <- purrr::map(pckgs, library, character.only=TRUE)
```

::: {.callout-important .disclaimer title='Disclaimer'}
Current draft describes work in progress and its content should be treated as such.  
The researcher should exhibit the necessary skepticism to ensure the analyses are appropriate.  
`{r} R.version.string`
:::

<!-- body -->

## Data

```{r}
#| label: data_read_rename_save
#| eval: false
dti <- haven::read_sav(mydata) |> zap_labels()
dtd <- readxl::read_excel(mydict, sheet='dict')
save(dti,dtd,file=paste0(prjct[['name']],'.RData'))
```

```{r}
#| label: load_data
.dta <- paste0(prjct[['name']],'.RData')
if(file.exists(.dta)) load(.dta)
```

## Analysis

## Conclusion

<!-- end -->

```{r}
#| label: save_image
time_image <- strftime(Sys.time(), format = "%y-%m-%d %H:%M")
save.image(paste0(prjct[['name']],'.IMAGE.RData'))
```
